//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 10:19:55 AM EAT 
//


package xmlparser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="invoicenr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="consigneeID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="countryofdestination" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pointofentry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="meansofconveyance" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="inspectionlocation" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="dateofdeparture" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="timeofdeparture" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;element name="preferredinspectiondate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="preferredinspectiontime" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;element name="distinguishingmarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="additionalinformation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="consignementweight" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="certificates">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="certificate">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="certificatetype" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="form" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="varietyquantities">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="varietyquantity">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="commoditytype" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="commoditycategory" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="commodityform" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="variety" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="numberofpackages" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="typeofpacking" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="treatmentdetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="treatmentdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="chemicalingredients" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="durationintemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="concentration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="producerID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="placeoforigin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "invoicenr",
    "consigneeID",
    "countryofdestination",
    "pointofentry",
    "meansofconveyance",
    "inspectionlocation",
    "dateofdeparture",
    "timeofdeparture",
    "preferredinspectiondate",
    "preferredinspectiontime",
    "distinguishingmarks",
    "additionalinformation",
    "consignementweight",
    "certificates",
    "varietyquantities"
})
@XmlRootElement(name = "consignement")
public class ECSConsignmentDoc {

    @XmlElement(required = true)
    protected String invoicenr;
    protected int consigneeID;
    @XmlElement(required = true)
    protected String countryofdestination;
    @XmlElement(required = true)
    protected String pointofentry;
    protected int meansofconveyance;
    protected int inspectionlocation;
    @XmlElement(required = true)
    protected String dateofdeparture;
    @XmlElement(required = true)
    @XmlSchemaType(name = "time")
    protected String timeofdeparture;
    @XmlElement(required = true)
    protected String preferredinspectiondate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "time")
    protected String preferredinspectiontime;
    @XmlElement(required = true)
    protected String distinguishingmarks;
    @XmlElement(required = true)
    protected String additionalinformation;
    protected double consignementweight;
    @XmlElement(required = true)
    protected ECSConsignmentDoc.Certificates certificates;
    @XmlElement(required = true)
    protected ECSConsignmentDoc.Varietyquantities varietyquantities;

    /**
     * Gets the value of the invoicenr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoicenr() {
        return invoicenr;
    }

    /**
     * Sets the value of the invoicenr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoicenr(String value) {
        this.invoicenr = value;
    }

    /**
     * Gets the value of the consigneeID property.
     * 
     */
    public int getConsigneeID() {
        return consigneeID;
    }

    /**
     * Sets the value of the consigneeID property.
     * 
     */
    public void setConsigneeID(int value) {
        this.consigneeID = value;
    }

    /**
     * Gets the value of the countryofdestination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryofdestination() {
        return countryofdestination;
    }

    /**
     * Sets the value of the countryofdestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryofdestination(String value) {
        this.countryofdestination = value;
    }

    /**
     * Gets the value of the pointofentry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointofentry() {
        return pointofentry;
    }

    /**
     * Sets the value of the pointofentry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointofentry(String value) {
        this.pointofentry = value;
    }

    /**
     * Gets the value of the meansofconveyance property.
     * 
     */
    public int getMeansofconveyance() {
        return meansofconveyance;
    }

    /**
     * Sets the value of the meansofconveyance property.
     * 
     */
    public void setMeansofconveyance(int value) {
        this.meansofconveyance = value;
    }

    /**
     * Gets the value of the inspectionlocation property.
     * 
     */
    public int getInspectionlocation() {
        return inspectionlocation;
    }

    /**
     * Sets the value of the inspectionlocation property.
     * 
     */
    public void setInspectionlocation(int value) {
        this.inspectionlocation = value;
    }

    /**
     * Gets the value of the dateofdeparture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateofdeparture() {
        return dateofdeparture;
    }

    /**
     * Sets the value of the dateofdeparture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateofdeparture(String value) {
        this.dateofdeparture = value;
    }

    /**
     * Gets the value of the timeofdeparture property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getTimeofdeparture() {
        return timeofdeparture;
    }

    /**
     * Sets the value of the timeofdeparture property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeofdeparture(String value) {
        this.timeofdeparture = value;
    }

    /**
     * Gets the value of the preferredinspectiondate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredinspectiondate() {
        return preferredinspectiondate;
    }

    /**
     * Sets the value of the preferredinspectiondate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredinspectiondate(String value) {
        this.preferredinspectiondate = value;
    }

    /**
     * Gets the value of the preferredinspectiontime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getPreferredinspectiontime() {
        return preferredinspectiontime;
    }

    /**
     * Sets the value of the preferredinspectiontime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPreferredinspectiontime(String value) {
        this.preferredinspectiontime = value;
    }

    /**
     * Gets the value of the distinguishingmarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistinguishingmarks() {
        return distinguishingmarks;
    }

    /**
     * Sets the value of the distinguishingmarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistinguishingmarks(String value) {
        this.distinguishingmarks = value;
    }

    /**
     * Gets the value of the additionalinformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalinformation() {
        return additionalinformation;
    }

    /**
     * Sets the value of the additionalinformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalinformation(String value) {
        this.additionalinformation = value;
    }

    /**
     * Gets the value of the consignementweight property.
     * 
     */
    public double getConsignementweight() {
        return consignementweight;
    }

    /**
     * Sets the value of the consignementweight property.
     * 
     */
    public void setConsignementweight(double value) {
        this.consignementweight = value;
    }

    /**
     * Gets the value of the certificates property.
     * 
     * @return
     *     possible object is
     *     {@link ECSConsignmentDoc.Certificates }
     *     
     */
    public ECSConsignmentDoc.Certificates getCertificates() {
        return certificates;
    }

    /**
     * Sets the value of the certificates property.
     * 
     * @param value
     *     allowed object is
     *     {@link ECSConsignmentDoc.Certificates }
     *     
     */
    public void setCertificates(ECSConsignmentDoc.Certificates value) {
        this.certificates = value;
    }

    /**
     * Gets the value of the varietyquantities property.
     * 
     * @return
     *     possible object is
     *     {@link ECSConsignmentDoc.Varietyquantities }
     *     
     */
    public ECSConsignmentDoc.Varietyquantities getVarietyquantities() {
        return varietyquantities;
    }

    /**
     * Sets the value of the varietyquantities property.
     * 
     * @param value
     *     allowed object is
     *     {@link ECSConsignmentDoc.Varietyquantities }
     *     
     */
    public void setVarietyquantities(ECSConsignmentDoc.Varietyquantities value) {
        this.varietyquantities = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="certificate">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="certificatetype" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="form" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "certificate"
    })
    public static class Certificates {

        @XmlElement(required = true)
        protected ECSConsignmentDoc.Certificates.Certificate certificate;

        /**
         * Gets the value of the certificate property.
         * 
         * @return
         *     possible object is
         *     {@link ECSConsignmentDoc.Certificates.Certificate }
         *     
         */
        public ECSConsignmentDoc.Certificates.Certificate getCertificate() {
            return certificate;
        }

        /**
         * Sets the value of the certificate property.
         * 
         * @param value
         *     allowed object is
         *     {@link ECSConsignmentDoc.Certificates.Certificate }
         *     
         */
        public void setCertificate(ECSConsignmentDoc.Certificates.Certificate value) {
            this.certificate = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="certificatetype" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="form" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "certificatetype",
            "form",
            "language"
        })
        public static class Certificate {

            protected byte certificatetype;
            @XmlElement(required = true)
            protected String form;
            @XmlElement(required = true)
            protected String language;

            /**
             * Gets the value of the certificatetype property.
             * 
             */
            public byte getCertificatetype() {
                return certificatetype;
            }

            /**
             * Sets the value of the certificatetype property.
             * 
             */
            public void setCertificatetype(byte value) {
                this.certificatetype = value;
            }

            /**
             * Gets the value of the form property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getForm() {
                return form;
            }

            /**
             * Sets the value of the form property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setForm(String value) {
                this.form = value;
            }

            /**
             * Gets the value of the language property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLanguage() {
                return language;
            }

            /**
             * Sets the value of the language property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLanguage(String value) {
                this.language = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="varietyquantity">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="commoditytype" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="commoditycategory" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="commodityform" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="variety" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="numberofpackages" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="typeofpacking" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="treatmentdetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="treatmentdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="chemicalingredients" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="durationintemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="concentration" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="producerID" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="placeoforigin" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "varietyquantity"
    })
    public static class Varietyquantities {

        @XmlElement(required = true)
        protected ECSConsignmentDoc.Varietyquantities.Varietyquantity varietyquantity;

        /**
         * Gets the value of the varietyquantity property.
         * 
         * @return
         *     possible object is
         *     {@link ECSConsignmentDoc.Varietyquantities.Varietyquantity }
         *     
         */
        public ECSConsignmentDoc.Varietyquantities.Varietyquantity getVarietyquantity() {
            return varietyquantity;
        }

        /**
         * Sets the value of the varietyquantity property.
         * 
         * @param value
         *     allowed object is
         *     {@link ECSConsignmentDoc.Varietyquantities.Varietyquantity }
         *     
         */
        public void setVarietyquantity(ECSConsignmentDoc.Varietyquantities.Varietyquantity value) {
            this.varietyquantity = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="commoditytype" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="commoditycategory" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="commodityform" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="variety" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="numberofpackages" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="typeofpacking" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="treatmentdetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="treatmentdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="chemicalingredients" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="durationintemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="concentration" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="producerID" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="placeoforigin" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "commoditytype",
            "commoditycategory",
            "commodityform",
            "variety",
            "quantity",
            "unit",
            "numberofpackages",
            "typeofpacking",
            "treatmentdetails",
            "treatmentdate",
            "chemicalingredients",
            "durationintemperature",
            "concentration",
            "producerID",
            "placeoforigin"
        })
        public static class Varietyquantity {

            protected short commoditytype;
            protected byte commoditycategory;
            protected byte commodityform;
            protected short variety;
            protected short quantity;
            protected byte unit;
            protected byte numberofpackages;
            protected short typeofpacking;
            @XmlElement(required = true)
            protected String treatmentdetails;
            @XmlElement(required = true)
            protected String treatmentdate;
            @XmlElement(required = true)
            protected String chemicalingredients;
            @XmlElement(required = true)
            protected String durationintemperature;
            @XmlElement(required = true)
            protected String concentration;
            protected short producerID;
            @XmlElement(required = true)
            protected String placeoforigin;

            /**
             * Gets the value of the commoditytype property.
             * 
             */
            public short getCommoditytype() {
                return commoditytype;
            }

            /**
             * Sets the value of the commoditytype property.
             * 
             */
            public void setCommoditytype(short value) {
                this.commoditytype = value;
            }

            /**
             * Gets the value of the commoditycategory property.
             * 
             */
            public byte getCommoditycategory() {
                return commoditycategory;
            }

            /**
             * Sets the value of the commoditycategory property.
             * 
             */
            public void setCommoditycategory(byte value) {
                this.commoditycategory = value;
            }

            /**
             * Gets the value of the commodityform property.
             * 
             */
            public byte getCommodityform() {
                return commodityform;
            }

            /**
             * Sets the value of the commodityform property.
             * 
             */
            public void setCommodityform(byte value) {
                this.commodityform = value;
            }

            /**
             * Gets the value of the variety property.
             * 
             */
            public short getVariety() {
                return variety;
            }

            /**
             * Sets the value of the variety property.
             * 
             */
            public void setVariety(short value) {
                this.variety = value;
            }

            /**
             * Gets the value of the quantity property.
             * 
             */
            public short getQuantity() {
                return quantity;
            }

            /**
             * Sets the value of the quantity property.
             * 
             */
            public void setQuantity(short value) {
                this.quantity = value;
            }

            /**
             * Gets the value of the unit property.
             * 
             */
            public byte getUnit() {
                return unit;
            }

            /**
             * Sets the value of the unit property.
             * 
             */
            public void setUnit(byte value) {
                this.unit = value;
            }

            /**
             * Gets the value of the numberofpackages property.
             * 
             */
            public byte getNumberofpackages() {
                return numberofpackages;
            }

            /**
             * Sets the value of the numberofpackages property.
             * 
             */
            public void setNumberofpackages(byte value) {
                this.numberofpackages = value;
            }

            /**
             * Gets the value of the typeofpacking property.
             * 
             */
            public short getTypeofpacking() {
                return typeofpacking;
            }

            /**
             * Sets the value of the typeofpacking property.
             * 
             */
            public void setTypeofpacking(short value) {
                this.typeofpacking = value;
            }

            /**
             * Gets the value of the treatmentdetails property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTreatmentdetails() {
                return treatmentdetails;
            }

            /**
             * Sets the value of the treatmentdetails property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTreatmentdetails(String value) {
                this.treatmentdetails = value;
            }

            /**
             * Gets the value of the treatmentdate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTreatmentdate() {
                return treatmentdate;
            }

            /**
             * Sets the value of the treatmentdate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTreatmentdate(String value) {
                this.treatmentdate = value;
            }

            /**
             * Gets the value of the chemicalingredients property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChemicalingredients() {
                return chemicalingredients;
            }

            /**
             * Sets the value of the chemicalingredients property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChemicalingredients(String value) {
                this.chemicalingredients = value;
            }

            /**
             * Gets the value of the durationintemperature property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDurationintemperature() {
                return durationintemperature;
            }

            /**
             * Sets the value of the durationintemperature property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDurationintemperature(String value) {
                this.durationintemperature = value;
            }

            /**
             * Gets the value of the concentration property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getConcentration() {
                return concentration;
            }

            /**
             * Sets the value of the concentration property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setConcentration(String value) {
                this.concentration = value;
            }

            /**
             * Gets the value of the producerID property.
             * 
             */
            public short getProducerID() {
                return producerID;
            }

            /**
             * Sets the value of the producerID property.
             * 
             */
            public void setProducerID(short value) {
                this.producerID = value;
            }

            /**
             * Gets the value of the placeoforigin property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPlaceoforigin() {
                return placeoforigin;
            }

            /**
             * Sets the value of the placeoforigin property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPlaceoforigin(String value) {
                this.placeoforigin = value;
            }

        }

    }
 
}
