//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.15 at 10:55:53 PM EAT 
//


package xmlparser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentHeader">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MsgId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="refno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="msg_func" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="sender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="receiver" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="msgdate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DocumentDetails">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="consignment_refnumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ver_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="certificate_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Permit_no" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="variety_inspection_remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="inspection_required" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="approval_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentHeader",
    "documentDetails"
})
@XmlRootElement(name = "KEPHISECS_Consignment_Inspection_Report")
public class KEPHISECSConsignmentInspectionReport {

    @XmlElement(name = "DocumentHeader", required = true)
    protected KEPHISECSConsignmentInspectionReport.DocumentHeader documentHeader;
    @XmlElement(name = "DocumentDetails", required = true)
    protected KEPHISECSConsignmentInspectionReport.DocumentDetails documentDetails;

    /**
     * Gets the value of the documentHeader property.
     * 
     * @return
     *     possible object is
     *     {@link KEPHISECSConsignmentInspectionReport.DocumentHeader }
     *     
     */
    public KEPHISECSConsignmentInspectionReport.DocumentHeader getDocumentHeader() {
        return documentHeader;
    }

    /**
     * Sets the value of the documentHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link KEPHISECSConsignmentInspectionReport.DocumentHeader }
     *     
     */
    public void setDocumentHeader(KEPHISECSConsignmentInspectionReport.DocumentHeader value) {
        this.documentHeader = value;
    }

    /**
     * Gets the value of the documentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link KEPHISECSConsignmentInspectionReport.DocumentDetails }
     *     
     */
    public KEPHISECSConsignmentInspectionReport.DocumentDetails getDocumentDetails() {
        return documentDetails;
    }

    /**
     * Sets the value of the documentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link KEPHISECSConsignmentInspectionReport.DocumentDetails }
     *     
     */
    public void setDocumentDetails(KEPHISECSConsignmentInspectionReport.DocumentDetails value) {
        this.documentDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="consignment_refnumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ver_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="certificate_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Permit_no" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="variety_inspection_remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="inspection_required" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="approval_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "consignmentRefnumber",
        "verNo",
        "certificateNo",
        "permitNo",
        "status",
        "remarks",
        "varietyInspectionRemarks",
        "inspectionRequired",
        "approvalType"
    })
    public static class DocumentDetails {

        @XmlElement(name = "consignment_refnumber", required = true)
        protected String consignmentRefnumber;
        @XmlElement(name = "ver_no", required = true)
        protected String verNo;
        @XmlElement(name = "certificate_no", required = true)
        protected String certificateNo;
        @XmlElement(name = "Permit_no")
        protected float permitNo;
        @XmlElement(required = true)
        protected String status;
        @XmlElement(required = true)
        protected String remarks;
        @XmlElement(name = "variety_inspection_remarks", required = true)
        protected String varietyInspectionRemarks;
        @XmlElement(name = "inspection_required", required = true)
        protected String inspectionRequired;
        @XmlElement(name = "approval_type", required = true)
        protected String approvalType;

        /**
         * Gets the value of the consignmentRefnumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConsignmentRefnumber() {
            return consignmentRefnumber;
        }

        /**
         * Sets the value of the consignmentRefnumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConsignmentRefnumber(String value) {
            this.consignmentRefnumber = value;
        }

        /**
         * Gets the value of the verNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVerNo() {
            return verNo;
        }

        /**
         * Sets the value of the verNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVerNo(String value) {
            this.verNo = value;
        }

        /**
         * Gets the value of the certificateNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCertificateNo() {
            return certificateNo;
        }

        /**
         * Sets the value of the certificateNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCertificateNo(String value) {
            this.certificateNo = value;
        }

        /**
         * Gets the value of the permitNo property.
         * 
         */
        public float getPermitNo() {
            return permitNo;
        }

        /**
         * Sets the value of the permitNo property.
         * 
         */
        public void setPermitNo(float value) {
            this.permitNo = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the remarks property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemarks() {
            return remarks;
        }

        /**
         * Sets the value of the remarks property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemarks(String value) {
            this.remarks = value;
        }

        /**
         * Gets the value of the varietyInspectionRemarks property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVarietyInspectionRemarks() {
            return varietyInspectionRemarks;
        }

        /**
         * Sets the value of the varietyInspectionRemarks property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVarietyInspectionRemarks(String value) {
            this.varietyInspectionRemarks = value;
        }

        /**
         * Gets the value of the inspectionRequired property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInspectionRequired() {
            return inspectionRequired;
        }

        /**
         * Sets the value of the inspectionRequired property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInspectionRequired(String value) {
            this.inspectionRequired = value;
        }

        /**
         * Gets the value of the approvalType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApprovalType() {
            return approvalType;
        }

        /**
         * Sets the value of the approvalType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApprovalType(String value) {
            this.approvalType = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MsgId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="refno" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="msg_func" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="sender" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="receiver" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="msgdate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "msgId",
        "refno",
        "msgFunc",
        "sender",
        "receiver",
        "version",
        "msgdate"
    })
    public static class DocumentHeader {

        @XmlElement(name = "MsgId", required = true)
        protected String msgId;
        @XmlElement(required = true)
        protected String refno;
        @XmlElement(name = "msg_func")
        protected int msgFunc;
        @XmlElement(required = true)
        protected String sender;
        @XmlElement(required = true)
        protected String receiver;
        protected double version;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected String msgdate;

        /**
         * Gets the value of the msgId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMsgId() {
            return msgId;
        }

        /**
         * Sets the value of the msgId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMsgId(String value) {
            this.msgId = value;
        }

        /**
         * Gets the value of the refno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefno() {
            return refno;
        }

        /**
         * Sets the value of the refno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefno(String value) {
            this.refno = value;
        }

        /**
         * Gets the value of the msgFunc property.
         * 
         */
        public int getMsgFunc() {
            return msgFunc;
        }

        /**
         * Sets the value of the msgFunc property.
         * 
         */
        public void setMsgFunc(int value) {
            this.msgFunc = value;
        }

        /**
         * Gets the value of the sender property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSender() {
            return sender;
        }

        /**
         * Sets the value of the sender property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSender(String value) {
            this.sender = value;
        }

        /**
         * Gets the value of the receiver property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReceiver() {
            return receiver;
        }

        /**
         * Sets the value of the receiver property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReceiver(String value) {
            this.receiver = value;
        }

        /**
         * Gets the value of the version property.
         * 
         */
        public double getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         */
        public void setVersion(double value) {
            this.version = value;
        }

        /**
         * Gets the value of the msgdate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public String getMsgdate() {
            return msgdate;
        }

        /**
         * Sets the value of the msgdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setMsgdate(String value) {
            this.msgdate = value;
        }

    }

}
