//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.06 at 08:19:47 PM EAT 
//


package xmlparser;

import javax.xml.bind.annotation.XmlRegistry;

import xmlparser.KESWSConsignmentDoc;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDImporter }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDImporter createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDImporter() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDImporter();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDConsignee }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDConsignee createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDConsignee() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDConsignee();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails createConsignmentDocumentDocumentDetailsConsignmentDocDetails() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentHeader.DocumentReference }
     * 
     */
    public KESWSConsignmentDoc.DocumentHeader.DocumentReference createConsignmentDocumentDocumentHeaderDocumentReference() {
        return new KESWSConsignmentDoc.DocumentHeader.DocumentReference();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.Attachments }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.Attachments createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDStandardTwoAttachments() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.Attachments();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDProductDetails() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDTransport.ContainerDetails }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDTransport.ContainerDetails createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDTransportContainerDetails() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDTransport.ContainerDetails();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentHeader.DocumentExchangeDetails }
     * 
     */
    public KESWSConsignmentDoc.DocumentHeader.DocumentExchangeDetails createConsignmentDocumentDocumentHeaderDocumentExchangeDetails() {
        return new KESWSConsignmentDoc.DocumentHeader.DocumentExchangeDetails();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.ApplicantDefinedThirdPartyDetails }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.ApplicantDefinedThirdPartyDetails createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDStandardTwoApplicantDefinedThirdPartyDetails() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.ApplicantDefinedThirdPartyDetails();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDProductDetailsItemDetails() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.ProcessingFee }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.ProcessingFee createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDStandardTwoProcessingFee() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.ProcessingFee();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDHeaderTwo }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDHeaderTwo createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDHeaderTwo() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDHeaderTwo();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentSummary }
     * 
     */
    public KESWSConsignmentDoc.DocumentSummary createConsignmentDocumentDocumentSummary() {
        return new KESWSConsignmentDoc.DocumentSummary();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.ThirdPartyDetails.ThirdParties }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.ThirdPartyDetails.ThirdParties createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDStandardTwoThirdPartyDetailsThirdParties() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.ThirdPartyDetails.ThirdParties();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandard.ServiceProvider }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandard.ServiceProvider createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDStandardServiceProvider() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandard.ServiceProvider();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDProduct1 }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDProduct1 createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDProductDetailsItemDetailsCDProduct1() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDProduct1();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDHdrNonStandard }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDHdrNonStandard createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDHdrNonStandard() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDHdrNonStandard();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.ThirdPartyDetails }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.ThirdPartyDetails createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDStandardTwoThirdPartyDetails() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.ThirdPartyDetails();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentHeader }
     * 
     */
    public KESWSConsignmentDoc.DocumentHeader createConsignmentDocumentDocumentHeader() {
        return new KESWSConsignmentDoc.DocumentHeader();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDHeaderOne }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDHeaderOne createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDHeaderOne() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDHeaderOne();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails createConsignmentDocumentDocumentDetails() {
        return new KESWSConsignmentDoc.DocumentDetails();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDItemCommodity }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDItemCommodity createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDProductDetailsItemDetailsCDItemCommodity() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDItemCommodity();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDTransport.ContainerDetails.Containers }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDTransport.ContainerDetails.Containers createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDTransportContainerDetailsContainers() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDTransport.ContainerDetails.Containers();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDItemNonStandard }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDItemNonStandard createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDProductDetailsItemDetailsCDItemNonStandard() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDItemNonStandard();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc }
     * 
     */
    public KESWSConsignmentDoc createConsignmentDocument() {
        return new KESWSConsignmentDoc();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDProduct2 .EndUserDetails }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDProduct2 .EndUserDetails createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDProductDetailsItemDetailsCDProduct2EndUserDetails() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDProduct2 .EndUserDetails();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDTransport }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDTransport createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDTransport() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDTransport();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.ApprovalDetails.ApprovalHistory }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.ApprovalDetails.ApprovalHistory createConsignmentDocumentDocumentDetailsConsignmentDocDetailsApprovalDetailsApprovalHistory() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.ApprovalDetails.ApprovalHistory();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDProduct2 .Attachments }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDProduct2 .Attachments createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDProductDetailsItemDetailsCDProduct2Attachments() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDProduct2 .Attachments();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.DocumentFee }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.DocumentFee createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDStandardTwoDocumentFee() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.DocumentFee();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.KEPHISHeaderFields }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.KEPHISHeaderFields createConsignmentDocumentDocumentDetailsConsignmentDocDetailsKEPHISHeaderFields() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.KEPHISHeaderFields();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDProduct1 .SupplementryQuantity }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDProduct1 .SupplementryQuantity createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDProductDetailsItemDetailsCDProduct1SupplementryQuantity() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDProduct1 .SupplementryQuantity();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDProduct1 .Quantity }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDProduct1 .Quantity createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDProductDetailsItemDetailsCDProduct1Quantity() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDProduct1 .Quantity();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDConsignor }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDConsignor createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDConsignor() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDConsignor();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDStandardTwo() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDProduct2 }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDProduct2 createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDProductDetailsItemDetailsCDProduct2() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDProductDetails.ItemDetails.CDProduct2();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDExporter }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDExporter createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDExporter() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDExporter();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.ApplicantDefinedThirdPartyDetails.ThirdParties }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.ApplicantDefinedThirdPartyDetails.ThirdParties createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDStandardTwoApplicantDefinedThirdPartyDetailsThirdParties() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandardTwo.ApplicantDefinedThirdPartyDetails.ThirdParties();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentHeader.DocumentExchangeDetails.ReceivingPartyDetails }
     * 
     */
    public KESWSConsignmentDoc.DocumentHeader.DocumentExchangeDetails.ReceivingPartyDetails createConsignmentDocumentDocumentHeaderDocumentExchangeDetailsReceivingPartyDetails() {
        return new KESWSConsignmentDoc.DocumentHeader.DocumentExchangeDetails.ReceivingPartyDetails();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandard }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandard createConsignmentDocumentDocumentDetailsConsignmentDocDetailsCDStandard() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.CDStandard();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.ApprovalDetails }
     * 
     */
    public KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.ApprovalDetails createConsignmentDocumentDocumentDetailsConsignmentDocDetailsApprovalDetails() {
        return new KESWSConsignmentDoc.DocumentDetails.ConsignmentDocDetails.ApprovalDetails();
    }

    /**
     * Create an instance of {@link KESWSConsignmentDoc.DocumentHeader.DocumentExchangeDetails.NotifyPartyDetails }
     * 
     */
    public KESWSConsignmentDoc.DocumentHeader.DocumentExchangeDetails.NotifyPartyDetails createConsignmentDocumentDocumentHeaderDocumentExchangeDetailsNotifyPartyDetails() {
        return new KESWSConsignmentDoc.DocumentHeader.DocumentExchangeDetails.NotifyPartyDetails();
    }
    public ECSConsignmentDoc.Certificates.Certificate createConsignementCertificatesCertificate() {
        return new ECSConsignmentDoc.Certificates.Certificate();
    }

    /**
     * Create an instance of {@link ECSConsignmentDoc }
     * 
     */
    public ECSConsignmentDoc createConsignement() {
        return new ECSConsignmentDoc();
    }

    /**
     * Create an instance of {@link ECSConsignmentDoc.Certificates }
     * 
     */
    public ECSConsignmentDoc.Certificates createConsignementCertificates() {
        return new ECSConsignmentDoc.Certificates();
    }

    /**
     * Create an instance of {@link ECSConsignmentDoc.Varietyquantities.Varietyquantity }
     * 
     */
    public ECSConsignmentDoc.Varietyquantities.Varietyquantity createConsignementVarietyquantitiesVarietyquantity() {
        return new ECSConsignmentDoc.Varietyquantities.Varietyquantity();
    }

    /**
     * Create an instance of {@link ECSConsignmentDoc.Varietyquantities }
     * 
     */
    public ECSConsignmentDoc.Varietyquantities createConsignementVarietyquantities() {
        return new ECSConsignmentDoc.Varietyquantities();
    }


    /**
     * Create an instance of {@link KEPHISECSConsignmentInspectionReport }
     * 
     */
    public KEPHISECSConsignmentInspectionReport createKEPHISECSConsignmentInspectionReport() {
        return new KEPHISECSConsignmentInspectionReport();
    }

    /**
     * Create an instance of {@link KEPHISECSConsignmentInspectionReport.DocumentHeader }
     * 
     */
    public KEPHISECSConsignmentInspectionReport.DocumentHeader createKEPHISECSConsignmentInspectionReportDocumentHeader() {
        return new KEPHISECSConsignmentInspectionReport.DocumentHeader();
    }

    /**
     * Create an instance of {@link KEPHISECSConsignmentInspectionReport.DocumentDetails }
     * 
     */
    public KEPHISECSConsignmentInspectionReport.DocumentDetails createKEPHISECSConsignmentInspectionReportDocumentDetails() {
        return new KEPHISECSConsignmentInspectionReport.DocumentDetails();
    }
}
